---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: lemmy
spec:
  ports:
  - name: http
    port: 8536
    targetPort: 8536
    protocol: TCP
  selector:
    app: lemmy
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: lemmy-ui
spec:
  ports:
  - name: http
    port: 1234
    targetPort: 1234
    protocol: TCP
  selector:
    app: lemmy-ui
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: pictrs
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: pictrs
  type: NodePort
